"""Add height and sex, make outcome nullable

Revision ID: fdbc1c213c83
Revises: 
Create Date: 2025-11-30 15:14:13.569913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbc1c213c83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('intubation_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('dtm', sa.Float(), nullable=True),
    sa.Column('dii', sa.Float(), nullable=True),
    sa.Column('mallampati', sa.Integer(), nullable=True),
    sa.Column('stop_bang', sa.Integer(), nullable=True),
    sa.Column('alganzouri', sa.Integer(), nullable=True),
    sa.Column('drug_used', sa.String(length=128), nullable=True),
    sa.Column('technique', sa.String(length=128), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('cormack', sa.Integer(), nullable=True),
    sa.Column('difficult_binary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intubation_record')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
